#!/bin/bash
#THIS FILE IS NO LONGER USED.  LEGACY LEFT FOR REFERENCE UNTIL v5.0
#Engineer: T Looby
#Date: 12/27/2023
#Description:  prepares docker context, then creates docker container
#              from dev machine

# remove previous build
rm -rf dockerDir

# make new docker staging directory for docker context
mkdir -p dockerDir/source/HEAT

# copy HEAT into the AppDir
cp -r github/*  dockerDir/source/HEAT/

# copy ORNL EFIT module
cp -r /home/tom/source/EFIT dockerDir/source/EFIT

# copy MAFOT bins and libs
mkdir -p dockerDir/opt/mafot/bin
mkdir -p dockerDir/opt/mafot/lib
cp -r /home/tom/source/HEAT/MAFOT/bin/* dockerDir/opt/mafot/bin/
cp -r /home/tom/source/HEAT/MAFOT/lib/* dockerDir/opt/mafot/lib/

#copy paraview bins and libs
mkdir -p dockerDir/opt/paraview/bin
mkdir -p dockerDir/opt/paraview/lib
cp -rn /opt/paraview/ParaView-5.10.1-MPI-Linux-Python3.9-x86_64/bin/* dockerDir/opt/paraview/bin/
cp -rn /opt/paraview/ParaView-5.10.1-MPI-Linux-Python3.9-x86_64/lib/* dockerDir/opt/paraview/lib/
cp -rn /opt/paraview/ParaView-5.10.1-MPI-Linux-Python3.9-x86_64/plugins/* dockerDir/opt/paraview/lib/

#copy v2112 openfoam
# copy openFoam bins and libs
mkdir -p dockerDir/opt/openfoam/lib
cp -rn /opt/openfoam/OpenFOAM-v2112/etc dockerDir/opt/openfoam/etc
cp -rn /opt/openfoam/OpenFOAM-v2112/bin dockerDir/opt/openfoam/bin
cp -rn /opt/openfoam/OpenFOAM-v2112/platforms dockerDir/opt/openfoam/platforms
# set up environment var files for openfoam inside container
rm dockerDir/opt/openfoam/etc/bashrc
mv dockerDir/opt/openfoam/etc/bashrc_HEAT dockerDir/opt/openfoam/etc/bashrc
rm dockerDir/opt/openfoam/etc/config.sh/setup
mv dockerDir/opt/openfoam/etc/config.sh/setupHEAT dockerDir/opt/openfoam/etc/config.sh/setup
#copy these files to the github repo so we dont lose them
cp -rn dockerDir/opt/openfoam/etc/bashrc github/source/openFoamTemplates/envFiles/
cp -rn dockerDir/opt/openfoam/etc/config.sh/setup github/source/openFoamTemplates/envFiles/

# copy swak4foam bins and libs (for groovyBC)
mkdir -p dockerDir/opt/swak4foam/bin
mkdir -p dockerDir/opt/swak4foam/lib
cp -rn /home/tom/OpenFOAM/tom-v2112/platforms/linux64GccDPInt32Opt/bin/* dockerDir/opt/swak4foam/bin/
cp -rn /home/tom/OpenFOAM/tom-v2112/platforms/linux64GccDPInt32Opt/lib/* dockerDir/opt/swak4foam/lib/

# copy Open3D bins and libs
#mkdir -p dockerDir/opt/open3d/bin
#mkdir -p dockerDir/opt/open3d/lib
#cp -rn /opt/open3d/Open3D/build/bin/* dockerDir/opt/open3d/bin/
#cp -rn /opt/open3d/Open3D/build/lib/* dockerDir/opt/open3d/lib/

#copy m3dc1 bins and libs
mkdir -p dockerDir/opt/m3dc1
cp -rn /opt/m3dc1/build/* dockerDir/opt/m3dc1/

#make file for docker build files
mkdir -p dockerDir/dockerBuildFiles
# copy python requirements file
cp -n requirements.txt dockerDir/
# copy dockerfile, recipes, bash scripts
cp -n buildDocker dockerDir/
cp -n docker-compose.yml dockerDir/
cp -n Dockerfile dockerDir/
cp -n runDockerCompose dockerDir/

#copy docker files to HEAT rootDir for uploading to github
#this clobbers old files
# copy python requirements file
cp requirements.txt /home/tom/source/HEAT/github/docker/
# copy dockerfile, recipes, bash scripts
cp buildDocker /home/tom/source/HEAT/github/docker/
cp docker-compose.yml /home/tom/source/HEAT/github/docker/
cp Dockerfile /home/tom/source/HEAT/github/docker/
cp runDockerCompose /home/tom/source/HEAT/github/docker/

#run docker build command
echo "Building docker image..."
cd dockerDir

#build for linux
docker build -t plasmapotential/heat .

#cross platform build (for apple silicon)
#docker buildx build --platform linux/amd64,linux/arm64 -t plasmapotential/heat -f ./Dockerfile . --push

#after creating image, tag it using the following command
# docker tag plasmapotential/heat:latest plasmapotential/heat:<tag>
#
#upload to dockerhub via the following command
# docker push plasmapotential/heat:<tag>
#
