#!/bin/bash
# Generate docker/.env with this machine's values. Idempotent: creates .env
# from .env.example if missing, then updates only the machine-specific keys,
# preserving any edits you have made (e.g. a pinned HEAT_IMAGE_TAG).
#
# Usage:
#   ./setup.sh          # generate/update .env
#   ./setup.sh --dev    # also write docker-compose.override.yml, which bind-
#                       # mounts this checkout over the image's HEAT clone so
#                       # local code changes run without rebuilding the image

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [ ! -f .env ]; then
  cp .env.example .env
  echo "Created .env from .env.example"
fi

# Replace key's value in .env, appending the key if absent.
set_kv() {
  local key="$1" value="$2"
  if grep -q "^${key}=" .env; then
    if sed --version 2>/dev/null | grep -q GNU; then
      sed -i "s|^${key}=.*|${key}=${value}|" .env
    else
      sed -i.bak "s|^${key}=.*|${key}=${value}|" .env && rm -f .env.bak
    fi
  else
    echo "${key}=${value}" >> .env
  fi
}

# UID for chown of HEAT output (see dockerUID/dockerGID in docker-compose.yml).
set_kv dockerUID "$(id -u)"

# GID: prefer the 'docker' group (files readable by all docker users), else
# the docker socket's group, else the caller's primary group.
if command -v getent >/dev/null 2>&1 && getent group docker >/dev/null 2>&1; then
  dockerGID="$(getent group docker | cut -d: -f3)"
elif [ -S /var/run/docker.sock ]; then
  # GNU stat first (-c), BSD/macOS fallback (-f). Not the reverse: GNU
  # `stat -f` prints filesystem info to stdout and would pollute the capture.
  dockerGID="$(stat -c '%g' /var/run/docker.sock 2>/dev/null || stat -f '%g' /var/run/docker.sock 2>/dev/null)"
  case "$dockerGID" in
    '' | *[!0-9]*) dockerGID="$(id -g)" ;;
  esac
else
  echo "No 'docker' group or docker socket found; using your primary group."
  dockerGID="$(id -g)"
fi
set_kv dockerGID "$dockerGID"

# HEAT data directory on the host (mounted at /root/HEAT).
HEAT_DATA_DIR="${HEAT_DATA_DIR:-$HOME/HEAT}"
mkdir -p "$HEAT_DATA_DIR"
set_kv HEAT_DATA_DIR "$HEAT_DATA_DIR"

echo "Wrote $SCRIPT_DIR/.env:"
grep -E '^(dockerUID|dockerGID|HEAT_DATA_DIR)=' .env

if [ "$1" = "--dev" ]; then
  REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
  # Both services need the mount: HEAT-gpu extends HEAT within the base file,
  # so it does NOT inherit volumes added here to HEAT alone.
  cat > docker-compose.override.yml <<EOF
# Auto-generated by setup.sh --dev. Bind-mounts your checkout over the HEAT
# source baked into the image, so local code changes run without a rebuild.
# Delete this file to revert to the image's built-in source.
services:
  HEAT:
    volumes:
      - type: bind
        source: ${REPO_ROOT}
        target: /root/source/HEAT
  HEAT-gpu:
    volumes:
      - type: bind
        source: ${REPO_ROOT}
        target: /root/source/HEAT
EOF
  echo "Wrote docker-compose.override.yml (dev mode: mounts ${REPO_ROOT} over /root/source/HEAT)"
fi
